### ISSUE TITLE
Signing and assured provenance of BAG data

### ISSUE THREAD

**Issue by glawes** [OpenNavigationSurface/WorkingGroup#7]
To encourage uptake of BAG for delivery of final survey data as a surface, the ability to assure provenance is a feature that helps to protect the liability of the surveyor. Is there a road-map to re-implement this capability since its removal from the v2.0.1 baseline and will the adoption of BAG as an OGC standard enforce any particular methodology?

It seems that this issue affects a variety of spatial data users, not just the hydrographic community, but there a limited means to produce assured spatial datasets generally. There may be an opportunity to leverage/participate in a parallel development that could apply more generally throughout a subset of OGC standards.

**Comment by brian-r-calder** [comment]
This was discussed at the CHC'24 WG meeting (#8) and received approval to move to an issue in the BAG repo, [here](https://github.com/OpenNavigationSurface/BAG/issues/113).  This issue is therefore complete.
